### ISSUE TITLE
How to get transparency in background color.

### ISSUE THREAD

**Issue by tg21** [jantari/poshwal#1]
I like the colors that script generates, but if I want like 10% transparency in background, how do I do that? 
![Screenshot (21)](https://user-images.githubusercontent.com/21080598/60501300-6fdb7380-9cd9-11e9-8917-c595c702b76e.png)

here at right side is cmd with 90% opacity and at left side windows terminal with theme generated by poshwal.

**Comment by jantari** [comment]
To add transparency to Windows Terminal, open the settings file and add:

    "useAcrylic" : true,
    "acrylicOpacity" : 0.90

to all the profiles. I won't add this to poshwal because Windows Terminal does not treat transparency as part of the theme, but as a seperate per-profile setting - and those I generally don't want to touch because I don't want to break them.
